# Generated by Django 4.1.4 on 2022-12-19 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=40, verbose_name='Nombre')),
                ('grado', models.IntegerField(verbose_name='Grado')),
                ('salon', models.CharField(max_length=20, verbose_name='Salon')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=2, verbose_name='Respuesta')),
                ('orden', models.IntegerField(verbose_name='Orden')),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('año', models.DateField(verbose_name='Año')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_estudiantes_resultados', to='authApp.estudiante')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_pregunta_resultados', to='authApp.pregunta')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_pruebas_resultados', to='authApp.prueba')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_pruebas_preguntas', to='authApp.prueba'),
        ),
    ]
